version: "3.3"
services:
  
  twtserver:
    image: davidBouman5DockerContainer.azurecr.io/twtserver:latest
    container_name: twtserver
    build:
      context: ./
      dockerfile: twtserver/Dockerfile
    ports: 
      - 9095
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1'  
    env_file:
      - ./.env
    networks:
      - twtnetwork

  twtclient:
    image: davidBouman5DockerContainer.azurecr.io/twtclient:latest
    container_name: twtclient
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1'
    build: 
      context: ./
      dockerfile: twtclient/Dockerfile
    env_file:
      - ./.env
    networks:
      - twtnetwork
    depends_on:
      - twtserver
  
  # mymodel:
  #   image: [containername].azurecr.io/twtmodel:latest
  #   container_name: twtmodel
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4G
  #         cpus: '1'
  #   build:
  #     context: ./
  #     dockerfile: twtmodel/Dockerfile
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - twtclient

networks:
  twtnetwork:
    driver: bridge
